# Generated by Django 4.2.5 on 2023-09-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0002_user_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='achievements/%Y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(to='events.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(to='users.achievements'),
        ),
    ]
