# Generated by Django 4.2.5 on 2023-09-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_activityproof_activity_activityproof_event'),
        ('users', '0003_alter_user_achievements_alter_user_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(blank=True, to='users.achievements'),
        ),
        migrations.AlterField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.event'),
        ),
    ]
