# Generated by Django 4.2.5 on 2023-09-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_fond_owner',
            field=models.BooleanField(default=False),
        ),
    ]
