# Generated by Django 4.2.5 on 2023-09-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_active'),
        ('users', '0007_user_owner_of_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events_done',
            field=models.ManyToManyField(blank=True, related_name='done', to='events.event'),
        ),
    ]
