# Generated by Django 4.2.5 on 2023-10-01 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_org'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='org',
            new_name='company',
        ),
    ]
