# Generated by Django 4.2.5 on 2023-09-30 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityproof',
            name='activity',
        ),
        migrations.AddField(
            model_name='activityproof',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='events.event'),
            preserve_default=False,
        ),
    ]
