# Generated by Django 4.2.5 on 2023-09-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_activityproof_eventproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventproof',
            name='сonfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
