# Generated by Django 4.2.5 on 2023-09-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventproof_сonfirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='proof_needs',
            field=models.SmallIntegerField(default=0),
        ),
    ]
