# Generated by Django 4.2.5 on 2023-09-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='active',
        ),
    ]
