# Generated by Django 4.2.5 on 2023-10-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coins',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
